version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "7000:7000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
